Metrics:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

require: rubocop-rake

Rake/Desc:
  Enabled: false
